name: abgrowers.com
favicon: null
layout_spectrum: 0.28198
typography_spectrum: 0.60239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#175200'
    - '#dde7d9'
    - '#5f884f'
    - '#a9c39f'
  brandStrength: 0.6994069293141365
  lightness: 0.2867179031018168
  saturation: 0.2952106068842113
  rhythmicContrast: 0.2062059671152383
purpose: []
